исправления в утилитах и в dl.py
bystrovpavelgit/foodrecommendationengine pull request #12
Opened 2022-10-22 19:05 UTC by bystrovpavelgit

исправления в утилитах и в dl.py

2022-10-24 16:48 UTC, technogleb requested changes

2022-10-24 16:48 UTC, technogleb commented on create_db.py
> +if __name__ == "__main__":
Переделать через app_context

2022-10-24 16:48 UTC, technogleb commented on prepare_nlp_data.py
> +    with app.app_context():
Здесь, наоборот, избавиться от app_context

2022-11-01 16:07 UTC, technogleb approved these changes

2022-11-12 07:02 UTC, bystrovpavelgit commented
merging

2022-11-12 07:02 UTC, merged